// XSD validation helper for Vitest. Wraps xmllint-wasm with a test-time
// master schema that pulls in every individual XSD and fills in a root
// element declaration for SpawnGroup (defined as a complexType but never
// declared as a top-level element in the upstream schema).

import { promises as fs } from 'fs'
import { join } from 'path'
import { validateXML } from 'xmllint-wasm'

const XSD_DIR = join(process.cwd(), 'xsd', 'src', 'XSD')

// Real XSDs present in the repo. Hybrasyl.xsd is excluded because it includes
// Formulas.xsd, which isn't shipped with the XML repo package.
const XSD_FILES = [
  'Common.xsd',
  'Item.xsd',
  'Castable.xsd',
  'ElementTable.xsd',
  'Creature.xsd',
  'Loot.xsd',
  'Map.xsd',
  'Nation.xsd',
  'ServerConfig.xsd',
  'Status.xsd',
  'Localization.xsd',
  'Recipe.xsd',
  'Spawns.xsd',
]

// Master schema — same namespace as the real XSDs. Pulls in every individual
// schema via xs:include so cross-type references resolve. Adds the missing
// top-level SpawnGroup element declaration.
const MASTER_XSD = `<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.hybrasyl.com/XML/Hybrasyl/2020-02"
           xmlns="http://www.hybrasyl.com/XML/Hybrasyl/2020-02"
           xmlns:hyb="http://www.hybrasyl.com/XML/Hybrasyl/2020-02"
           elementFormDefault="qualified">
${XSD_FILES.map((f) => `  <xs:include schemaLocation="${f}" />`).join('\n')}
  <xs:element name="SpawnGroup" type="hyb:SpawnGroup" />
</xs:schema>
`

/**
 * Defensive fix for upstream XSD issues that cause xmllint to fail at schema
 * compile time. Applied on read so the shipped XSD files (regenerated by
 * scripts/downloadXSD.js) stay untouched.
 *
 * Known issues patched:
 * - Trailing whitespace inside type="..." attribute values (e.g. Common.xsd's
 *   `type="CreatureCookies "` / `type="CreatureImmunities "`).
 */
function sanitizeXsd(contents) {
  return contents.replace(/type="([^"]*?)\s+"/g, 'type="$1"')
}

let cachedPreload = null

async function loadPreload() {
  if (cachedPreload) return cachedPreload
  const preload = []
  for (const name of XSD_FILES) {
    const raw = await fs.readFile(join(XSD_DIR, name), 'utf-8')
    preload.push({ fileName: name, contents: sanitizeXsd(raw) })
  }
  cachedPreload = preload
  return preload
}

/**
 * Validate an XML string against the Hybrasyl schema collection.
 * Returns { valid, errors } per xmllint-wasm's contract.
 *
 * @param {string} xml - XML document to validate
 * @param {string} [fileName='test.xml'] - file name reported in error messages
 */
export async function validateHybrasylXml(xml, fileName = 'test.xml') {
  const preload = await loadPreload()
  const result = await validateXML({
    xml: [{ fileName, contents: xml }],
    schema: [MASTER_XSD],
    preload,
    initialMemoryPages: 256,
  })
  return result
}
